
var languages = {
    "default_lang": "de",
    "privacy_policy": "Datenschutzrichtlinien",
    "disclaimer": "Prüfen Sie vor der Abfahrt die Echtzeit-Ankünfte an der Haltestelle und die Meldungen, die Ihre Fahrt beeinflussen können. Zeiten und Wege sind nur für Planungszwecke gedacht und können aufgrund von Verkehr, Straßenzustand, Abweichungen und anderen Faktoren wechseln.",
    "tnc": "Nutzungsbedingungen",
    "south": "Süd",
    "north": "Nord",
    "west": "Westen",
    "east": "Osten",
    "north_west": "Nord-Westen",
    "north_east": "Nord-Osten",
    "south_west": "Süd-Westen",
    "south_east": "Süd-Osten",
    "walk_for": "Gehe zu",
    "ride_for": "Fahre zu",
    "go_to": "Fahre zu",
    "right": "rechts",
    "left": "links",
    "hard_right": "Alles rechts",
    "hard_left": "Alles links",
    "slighly_right": "Leicht nach rechts",
    "slighly_left": "Leicht nach links",
    "continue": "Gehe weiter",
    "elevator": "Den Aufzug nehmen",
    "right_uturn": "Rechts abbiegen",
    "left_uturn": "Links abbiegen",
    "circle_clock": "Dem Kreisverkehr im Uhrzeigersinn folgen",
    "circle_counterclock": "Dem Kreisverkehr gegen den Uhrzeigersinn folgen",
    "details_trip": "Fahrtendetails",
    "calories": "Verbrannte Kalorien",
    "calories_info_1": "Die verbrannten Kalorien basieren auf",
    "minute": "Minute(n)",
    "at_time": "um",
    "pass_walked": "zu Fuß verbracht und",
    "pass_rided": "auf dieser Fahrt verbracht. Angepasst von",
    "drive_for": "Fahren Sie",
    "travel_for": "Reisen Sie",
    "drive": "Fahren Sie",
    "copy": "Link kopieren",
    "copied": "Kopiert",
    "print": "Drucken",
    "report": "Bericht",
    "restart": "Neustart",
    "altimetry": "Altimetrie",
    "altimetry_unavailable": "Altimetrie nicht verfügbar",
    "option": "Option",
    "options": "Optionen",
    "found": "Gefunden",
    "wait": "Bitte warten",
    "from_here": "Von hier",
    "to_here": "Zu hier",
    "travel": "Reise",
    "service": "Dienst durchgeführt von",
    "to": "nach",
    "on": "auf",
    "take": "Nehmen Sie",
    "home": "Hause",
    "work": "Arbeit",
    "yes": "Ja",
    "no": "Nein",
    "storage_disclaimer": "Jede Präferenz, jeder Ort und jede Einstellung, für die Sie sich entschieden haben, wird im lokalen Speicher Ihres Browsers gespeichert. Kein Außenstehender wird den Ort Ihres Zuhauses, Ihrer Arbeit oder anderer Orte kennen. Sie können jederzeit entscheiden, die Speicherung zu beenden und die Daten zu entfernen.",
    "route_viewer": "Linien anzeigen",
    "route_view_details": "Wählen Sie eine Linie aus, die auf der Karte angezeigt werden soll, und sehen Sie weitere Informationen zu dieser Linie.",
    "trip": "Fahrt",
    "stop": "Haltestelle",
    "plan_trip": "Fahrt planen",
    "hide_settings": "Einstellungen ausblenden",
    "now": "jetzt",
    "depart_at": "Abfahrt um",
    "arrive_at": "Ankunft at",
    "settings": "Einstellungen",
    "arrive": "Ankunft",
    "departure": "Abfahrt",
    "preferences": "Reisepräferenzen",
    "forget_settings": "Einstellungen vergessen",
    "tpl": "Öffentliche Verkehrsmittel",
    "by_walk": "zu Fuß",
    "by_bike": "Mit Fahrrad",
    "meter": "Meter",
    "bus": "Bus",
    "stops": "Haltestellen",
    "trip_view": "Fahrtdetails",
    "train": "Zug",
    "my_bike": "Persönliches Fahrrad",
    "add": "hinfügen",
    "favorite_stops": "Beliebte Haltestellen",
    "my_preferences": "Meine Präferenzen",
    "save_researches": "An die letzten Suchen und Orte erinnern?",
    "clear": "Löschen",
    "switch": "Standort wechseln",
    "insert_departure": "Abfahrt einfügen oder",
    "insert_arrive": "Ankunft einfügen oder",
    "on_map": "auf der Karte",
    "tap": "tippen",
    "click": "Klick",
    "use_current_position": "Aktuelle Position verwenden",
    "back": "zurück",
    "reset_the": "Zurücksetzen ",
    "my": "mein",
    "settings2": "Einstellungen",
    "transfers": "Anschlüsse",
    "transfer": "Anschluss",
    "walk_speed": "Gehgeschwindigkeit",
    "ride_speed": "Fahrradgeschwindigkeit",
    "optimizer": "Optimieren",
    "speed": "Geschwindigkeit",
    "less_transfers": "Wenigere Anschlüsse",
    "security": "Sicherheit",
    "flat": "flach",
    "mode": "verwenden",
    "sidewalk": "Fußweg",
    "bike_path": "Radweg",
    "steps": "Schritte",
    "track": "path",
    "path": "Strasse ohne Name",
    "road": "namenloser Weg",
    "allowed": "Erlaubt",
    "available": "Zugänglich",
    "available_wheelchair": "Rollstuhlgängig",
    "schedule": "Zeitplan",
    "next": "demnächst verfügbar",
    "show": "anzeigen",
    "direction": "nach",
    "departure_cap": "ABFAHREN",
    "mean_cap": "BLOCK",
    "status_cap": "STATUS",
    "refresh_arrival": "Auto-Refresh-Ankünfte?",
    "scheduled": "geplant",
    "save_as_home": "Als Zuhause speichern",
    "forget_home": "Zuhause vergessen",
    "forget_work": "Arbeit vergessen",
    "save_as_work": "Als Arbeit speichern",
    "remove_as": "Löschen als",
    "schedule2": "geplant",
    "origin": "Startpunkt",
    "destination": "Endpunkt",
    "change_as": "Ändern als",
    "get_on": "Weitergehen",
    "drop_off": "Aussteigen",
    "from": "Abfahren",
    "from2": "von",
    "stay_onboard_at": "Bleiben Sie an Bord von",
    "continues_as": "Weiter als",
    "map": "Karte",
    "itinerary": "Reiseverlauf",
    "where_go": "Wohin möchten Sie gehen?",
    "type_location": "Standort eingeben",
    "set": "Einstellen",
    "set_time": "Datum/Uhrzeit einstellen",
    "set_search": "Suche einstellen",
    "edit": "Bearbeiten",
    "no_favorite_stops": "Keine Lieblingshaltestellen",
    "remember_settings": "Reiseoptionen merken",
    "funicular": "Seilbahn"
};
