name: "Build and push calculate"

on: 
  workflow_dispatch:
  push:

env:
  PROJECT_NAME: "odh-mentor-otp-calculate"
  API_HOST: http://localhost
  API_PATH: /otp/routers/openmove
  API_PORT: 8080
  DOCKER_IMAGE_OTP: ghcr.io/${{ github.repository }}/odh-mentor-otp-calculate
  DOCKER_TAG: ${{ github.sha }}

jobs:
  ci-calculate:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prod'
    concurrency: build-calc
    steps:
      - name: Checkout source code
        uses: noi-techpark/github-actions/checkout@v2

      - name: Build and push 
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          docker-compose-file: docker-compose.build.calculate.yml
